---
language: node_js
node_js:
- '0.10'
services:
- neo4j
before_script:
- npm install -g grunt-cli
addons:
  sauce_connect: true
deploy:
  provider: heroku
  app: agilejs-localhorsts
  strategy: git
  api_key:
    secure: ! 'DzhquADWVKvvFr022ikl8PYOjw3ayYGBlLDVBD4DfAZsqGK4IYZNTezcH2W0

      ix/vLb9s902gUbpm3TsbrE0yXPoY3aOxuHyRl4HUxGnSsudv4uky3BZ5Wn0S

      OZpPxaDpezuP6yIwFyyjQgB6VzMZ3PV85XvcjwgoKtzZZqGxch0='
env:
  global:
  - secure: d49L3Mhz/hgqKm4k0XTJy5RY+oxBFbGML1e4rPqSde3J4gK5jhV0FbYeX1NC9rJI8NyVQhDy/Il20tlhLwGUANy1bwuXG7zAgHlR89wVD4e9M9XT2OEsZkb0mIosEeL7d1V7gGELWUvYSJyLVdfo/wOQP7lZQhHNw9of2BOpmOA=
  - secure: giUGZ1CVf4R5+unFH2BHYBeBOBCLW4BlU78kOyQ6HzeVovCHO8zsqppj7x9NU5SsDPUZz6yGAttqLFA0jpgBPRbYGqx+901FrOBKYWRb/i8IgDn0RYJnsEibBFiOFwJ+EAiG+CCCr6YM5N70MfZk7Pt+tQbRdfHTjesbEAUNuyc=
