language: node_js
node_js:
- '0.10'
services:
- neo4j
before_script:
- npm install -g grunt-cli
addons:
  sauce_connect: true
deploy:
  provider: heroku
  app: movie-database-node
  api_key:
    secure: LfX4hB0xQv9z4ZD+Iiz0tffiNceHyB4/wfeFacra7m9xLpjtpqOmBvbQGzl3 3EGek2clup/ri2RHHQm5QCqK5L8ohptvHSoBusghHmXyV80knIb8mlnpmwMe
      7Vs7v9wdALHudWPHly9pN0OZHxYsRprQc8R6b2rowAdMxzMraDg=
env:
  global:
  - secure: d49L3Mhz/hgqKm4k0XTJy5RY+oxBFbGML1e4rPqSde3J4gK5jhV0FbYeX1NC9rJI8NyVQhDy/Il20tlhLwGUANy1bwuXG7zAgHlR89wVD4e9M9XT2OEsZkb0mIosEeL7d1V7gGELWUvYSJyLVdfo/wOQP7lZQhHNw9of2BOpmOA=
  - secure: giUGZ1CVf4R5+unFH2BHYBeBOBCLW4BlU78kOyQ6HzeVovCHO8zsqppj7x9NU5SsDPUZz6yGAttqLFA0jpgBPRbYGqx+901FrOBKYWRb/i8IgDn0RYJnsEibBFiOFwJ+EAiG+CCCr6YM5N70MfZk7Pt+tQbRdfHTjesbEAUNuyc=
